# dsa/search/Makefile

# Include the common Makefile
include ../../Makefile.common

# Additional rules specific to this directory
run:
	@clear
	@echo -e "Running the program\n"
	@sudo ./$(OBJDIR)/linearSearch.o